### ISSUE TITLE
Erroneous data in dslabs::us_contagious_diseases

### ISSUE THREAD

**Issue by oranwutang** [rafalab/dslabs#6]
Hi, 

I have detected that data in dslabs::us_contagious_diseases must be erroneous, polio cases are surely wrong, according to this data polio in the US is increasing in the last years which is obviously false. By the way, results are exactly the same as pertussis so there should be the source of the problem.

![diseases](https://user-images.githubusercontent.com/6965617/70744011-2d56a200-1d21-11ea-8f92-70eeebc4a8d4.png)

The code to make the plot is as follows:

```
library(tidyverse)
library(lubridate)
library(magrittr)

diseases <- dslabs::us_contagious_diseases

diseases %>%
  filter(year > 1960) %>%
  group_by(disease, year) %>%
  summarise(Incidence = sum(count) / sum(population) * 100000) %>%
  ggplot(aes(year, Incidence)) +
    geom_step(aes(color = disease)) +
    facet_wrap(vars(disease), scales = "free") +
    theme(legend.position = "NA")
```

Best regards.

**Comment by rafalab** [comment]
Thanks! I fixed this. It might take a few days to get to CRAN. You can get a the fixed version like this:

```
devtools::install_github("rafalab/dslabs")
```

Try it out if you get a chance and let me know if you find any other problem.

**Comment by oranwutang** [comment]
Now it is correct. Thanks for your quick response!
![Rplot](https://user-images.githubusercontent.com/6965617/70794364-c7f4c680-1d9d-11ea-9330-d61de3c1c7f5.png)
